CREATE TABLE vehicles (
    Kenteken varchar(50),
    Voertuigsoort varchar(50),
    Merk varchar(50),
    Handelsbenaming varchar(50),
    `Vervaldatum APK` int(11),
    `Datum tenaamstelling` int(11),
    `Bruto BPM` int(11),
    Inrichting varchar(50),
    `Aantal zitplaatsen` int(11),
    `Eerste kleur` varchar(50),
    `Tweede kleur` varchar(50),
    `Aantal cilinders` int(11),
    `Cilinderinhoud` int(11),
    `Massa ledig voertuig` int(11),
    `Toegestane maximum massa voertuig` int(11),
    `Massa rijklaar` int(11),
    `Maximum massa trekken ongeremd` int(11),
    `Maximum trekken massa geremd` int(11),
    `Datum eerste toelating` int(11),
    `Datum eerste tenaamstelling in Nederland` int(11),
    `Wacht op keuren` varchar(50),
    `Catalogusprijs` int(11),
    `WAM verzekerd` varchar(50),
    `Maximale constructiesnelheid` int(11),
    `Laadvermogen` int(11),
    `Oplegger geremd` int(11),
    `Aanhangwagen autonoom geremd` int(11),
    `Aanhangwagen middenas geremd` int(11),
    `Aantal staanplaatsen` int(11),
    `Aantal deuren` int(11),
    `Aantal wielen` int(11),
    `Afstand hart koppeling tot achterzijde voertuig` int(11),
    `Afstand voorzijde voertuig tot hart koppeling` int(11),
    `Afwijkende maximum snelheid` int(11),
    Lengte int(11),
    Breedte int(11),
    `Europese voertuigcategorie` varchar(50),
    `Europese voertuigcategorie toevoeging` varchar(50),
    `Europese uitvoeringcategorie toevoeging` varchar(50),
    `Plaats chassisnummer` varchar(50),
    `Technische max. massa voertuig` int(11),
    `Type` varchar(50),
    `Type gasinstallatie` varchar(50),
    `Typegoedkeuringsnummer` varchar(50),
    `Variant` varchar(50),
    `Uitvoering` varchar(50),
    `Volgnummer wijziging EU typegoedkeuring` int(11),
    `Vermogen massarijklaar` int(11),
    `Wielbasis` int(11),
    `Export indicator` varchar(50),
    `Openstaande terugroepactie indicator` varchar(50),
    `Vervaldatum tachograaf` int(11),
    `Taxi indicator` varchar(50),
    `Maximum massa samenstelling` int(11),
    `Aantal rolstoelplaatsen` int(11),
    `Maximum ondersteunende snelheid` int(11),
    `Jaar laatste registratie tellerstand` int(11),
    `Tellerstandoordeel` varchar(50),
    `Code toelichting tellerstandoordeel` varchar(50),
    `Tenaamstellen mogelijk` varchar(50),
    `Vervaldatum APK DT` datetime,
    `Datum tenaamstelling DT` datetime,
    `Datum eerste toelating DT` datetime,
    `Datum eerste tenaamstelling in Nederland DT` datetime,
    `Vervaldatum tachograaf DT` datetime,
    `Maximum last onder de vooras(sen) (tezamen)/koppeling` int(11),
    `Type remsysteem voertuig code` varchar(50),
    `Rupsonderstelconfiguratiecode` varchar(50),
    `Wielbasis voertuig minimum` int(11),
    `Wielbasis voertuig maximum` int(11),
    `Lengte voertuig minimum` int(11),
    `Lengte voertuig maximum` int(11),
    `Breedte voertuig minimum` int(11),
    `Breedte voertuig maximum` int(11),
    `Hoogte voertuig` int(11),
    `Hoogte voertuig minimum` int(11),
    `Hoogte voertuig maximum` int(11),
    `Massa bedrijfsklaar minimaal` int(11),
    `Massa bedrijfsklaar maximaal` int(11),
    `Technisch toelaatbaar massa koppelpunt` int(11),
    `Maximum massa technisch maximaal` int(11),
    `Maximum massa technisch minimaal` int(11),
    `Subcategorie Nederland` varchar(50),
    `Verticale belasting koppelpunt getrokken voertuig` int(11),
    `Zuinigheidsclassificatie` varchar(50),
    `Registratie datum goedkeuring (afschrijvingsmoment BPM)` int(11),
    `Registratie datum goedkeuring (afschrijvingsmoment BPM) DT` datetime,
    `Gemiddelde Lading Waarde` int(11),
    `Aerodynamische voorziening of uitrusting` varchar(50),
    `Additionele massa alternatieve aandrijving` int(11),
    `Verlengde cabine indicator` varchar(50),
    `API Gekentekende_voertuigen_assen` varchar(50),
    `API Gekentekende_voertuigen_brandstof` varchar(50),
    `API Gekentekende_voertuigen_carrosserie` varchar(50),
    `API Gekentekende_voertuigen_carrosserie_specifiek` varchar(50),
    `API Gekentekende_voertuigen_voertuigklasse` varchar(50);
);
